// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NspDay09LabCF.Models;

#nullable disable

namespace NspDay09LabCF.Migrations
{
    [DbContext(typeof(NspDay09LabCFContext))]
    partial class NspDay09LabCFContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NspDay09LabCF.Models.NspLoai_San_Pham", b =>
                {
                    b.Property<long>("nspId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("nspId"));

                    b.Property<string>("nspMaLoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("nspTenLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("nspTrangThai")
                        .HasColumnType("bit");

                    b.HasKey("nspId");

                    b.HasIndex("nspMaLoai")
                        .IsUnique();

                    b.ToTable("NspLoai_San_Pham");
                });

            modelBuilder.Entity("NspDay09LabCF.Models.NspSan_Pham", b =>
                {
                    b.Property<long>("nspId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("nspId"));

                    b.Property<decimal>("nspDonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("nspHinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("nspLoaiSanPhamId")
                        .HasColumnType("bigint");

                    b.Property<long>("nspLoai_San_PhamnspId")
                        .HasColumnType("bigint");

                    b.Property<string>("nspMaSanPham")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("nspSoLuong")
                        .HasColumnType("int");

                    b.Property<string>("nspTenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("nspId");

                    b.HasIndex("nspLoai_San_PhamnspId");

                    b.ToTable("NspSan_Pham");
                });

            modelBuilder.Entity("NspDay09LabCF.Models.NspSan_Pham", b =>
                {
                    b.HasOne("NspDay09LabCF.Models.NspLoai_San_Pham", "nspLoai_San_Pham")
                        .WithMany("nspSan_Phams")
                        .HasForeignKey("nspLoai_San_PhamnspId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("nspLoai_San_Pham");
                });

            modelBuilder.Entity("NspDay09LabCF.Models.NspLoai_San_Pham", b =>
                {
                    b.Navigation("nspSan_Phams");
                });
#pragma warning restore 612, 618
        }
    }
}
